//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchChatinator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchUsername {
            get {
                return ((string)(this["TwitchUsername"]));
            }
            set {
                this["TwitchUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchPassword {
            get {
                return ((string)(this["TwitchPassword"]));
            }
            set {
                this["TwitchPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwithChannel {
            get {
                return ((string)(this["TwithChannel"]));
            }
            set {
                this["TwithChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLite")]
        public string StorageEngine {
            get {
                return ((string)(this["StorageEngine"]));
            }
            set {
                this["StorageEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000000")]
        public string PollChromaKey {
            get {
                return ((string)(this["PollChromaKey"]));
            }
            set {
                this["PollChromaKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PollAllowMulti {
            get {
                return ((bool)(this["PollAllowMulti"]));
            }
            set {
                this["PollAllowMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string PollOption1 {
            get {
                return ((string)(this["PollOption1"]));
            }
            set {
                this["PollOption1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string PollOption2 {
            get {
                return ((string)(this["PollOption2"]));
            }
            set {
                this["PollOption2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PollOption3 {
            get {
                return ((string)(this["PollOption3"]));
            }
            set {
                this["PollOption3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PollOption4 {
            get {
                return ((string)(this["PollOption4"]));
            }
            set {
                this["PollOption4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000191255")]
        public string PollOption1Color {
            get {
                return ((string)(this["PollOption1Color"]));
            }
            set {
                this["PollOption1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219112147")]
        public string PollOption2Color {
            get {
                return ((string)(this["PollOption2Color"]));
            }
            set {
                this["PollOption2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124252000")]
        public string PollOption3Color {
            get {
                return ((string)(this["PollOption3Color"]));
            }
            set {
                this["PollOption3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255165000")]
        public string PollOption4Color {
            get {
                return ((string)(this["PollOption4Color"]));
            }
            set {
                this["PollOption4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PollLeftMargin {
            get {
                return ((int)(this["PollLeftMargin"]));
            }
            set {
                this["PollLeftMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PollRightMargin {
            get {
                return ((int)(this["PollRightMargin"]));
            }
            set {
                this["PollRightMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PollTopMargin {
            get {
                return ((int)(this["PollTopMargin"]));
            }
            set {
                this["PollTopMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PollBottomMargin {
            get {
                return ((int)(this["PollBottomMargin"]));
            }
            set {
                this["PollBottomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PollBarHeight {
            get {
                return ((int)(this["PollBarHeight"]));
            }
            set {
                this["PollBarHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int PollBarWidth {
            get {
                return ((int)(this["PollBarWidth"]));
            }
            set {
                this["PollBarWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string PollFontName {
            get {
                return ((string)(this["PollFontName"]));
            }
            set {
                this["PollFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public float PollTitleSize {
            get {
                return ((float)(this["PollTitleSize"]));
            }
            set {
                this["PollTitleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255255255")]
        public string PollTitleColor {
            get {
                return ((string)(this["PollTitleColor"]));
            }
            set {
                this["PollTitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float PollCountSize {
            get {
                return ((float)(this["PollCountSize"]));
            }
            set {
                this["PollCountSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255255255")]
        public string PollCountColor {
            get {
                return ((string)(this["PollCountColor"]));
            }
            set {
                this["PollCountColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public float PollTotalSize {
            get {
                return ((float)(this["PollTotalSize"]));
            }
            set {
                this["PollTotalSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255255255")]
        public string PollTotalColor {
            get {
                return ((string)(this["PollTotalColor"]));
            }
            set {
                this["PollTotalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int PollTotalWidth {
            get {
                return ((int)(this["PollTotalWidth"]));
            }
            set {
                this["PollTotalWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int PollBarSpacing {
            get {
                return ((int)(this["PollBarSpacing"]));
            }
            set {
                this["PollBarSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PollWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["PollWindowLocation"]));
            }
            set {
                this["PollWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RollLeftMargin {
            get {
                return ((int)(this["RollLeftMargin"]));
            }
            set {
                this["RollLeftMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RollRightMargin {
            get {
                return ((int)(this["RollRightMargin"]));
            }
            set {
                this["RollRightMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RollTopMargin {
            get {
                return ((int)(this["RollTopMargin"]));
            }
            set {
                this["RollTopMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RollBottomMargin {
            get {
                return ((int)(this["RollBottomMargin"]));
            }
            set {
                this["RollBottomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int RollTotalWidth {
            get {
                return ((int)(this["RollTotalWidth"]));
            }
            set {
                this["RollTotalWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color RollTitleColor {
            get {
                return ((global::System.Drawing.Color)(this["RollTitleColor"]));
            }
            set {
                this["RollTitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color RollRollerColor {
            get {
                return ((global::System.Drawing.Color)(this["RollRollerColor"]));
            }
            set {
                this["RollRollerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color RollEntriesColor {
            get {
                return ((global::System.Drawing.Color)(this["RollEntriesColor"]));
            }
            set {
                this["RollEntriesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Roll")]
        public string RollRollerText {
            get {
                return ((string)(this["RollRollerText"]));
            }
            set {
                this["RollRollerText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 24pt")]
        public global::System.Drawing.Font RollTitleFont {
            get {
                return ((global::System.Drawing.Font)(this["RollTitleFont"]));
            }
            set {
                this["RollTitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 28pt")]
        public global::System.Drawing.Font RollRollerFont {
            get {
                return ((global::System.Drawing.Font)(this["RollRollerFont"]));
            }
            set {
                this["RollRollerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 16pt")]
        public global::System.Drawing.Font RollEntriesFont {
            get {
                return ((global::System.Drawing.Font)(this["RollEntriesFont"]));
            }
            set {
                this["RollEntriesFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RollChromaKey {
            get {
                return ((global::System.Drawing.Color)(this["RollChromaKey"]));
            }
            set {
                this["RollChromaKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RollEntriesTop {
            get {
                return ((int)(this["RollEntriesTop"]));
            }
            set {
                this["RollEntriesTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RollRollerTop {
            get {
                return ((int)(this["RollRollerTop"]));
            }
            set {
                this["RollRollerTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GIVEAWAY")]
        public string RollTitleText {
            get {
                return ((string)(this["RollTitleText"]));
            }
            set {
                this["RollTitleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point RollWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["RollWindowLocation"]));
            }
            set {
                this["RollWindowLocation"] = value;
            }
        }
    }
}
