//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchChatinator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchUsername {
            get {
                return ((string)(this["TwitchUsername"]));
            }
            set {
                this["TwitchUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchPassword {
            get {
                return ((string)(this["TwitchPassword"]));
            }
            set {
                this["TwitchPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwithChannel {
            get {
                return ((string)(this["TwithChannel"]));
            }
            set {
                this["TwithChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SQLite")]
        public string StorageEngine {
            get {
                return ((string)(this["StorageEngine"]));
            }
            set {
                this["StorageEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000000")]
        public string PollChromaKey {
            get {
                return ((string)(this["PollChromaKey"]));
            }
            set {
                this["PollChromaKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PollAllowMulti {
            get {
                return ((bool)(this["PollAllowMulti"]));
            }
            set {
                this["PollAllowMulti"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string PollOption1 {
            get {
                return ((string)(this["PollOption1"]));
            }
            set {
                this["PollOption1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string PollOption2 {
            get {
                return ((string)(this["PollOption2"]));
            }
            set {
                this["PollOption2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PollOption3 {
            get {
                return ((string)(this["PollOption3"]));
            }
            set {
                this["PollOption3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PollOption4 {
            get {
                return ((string)(this["PollOption4"]));
            }
            set {
                this["PollOption4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000191255")]
        public string PollOption1Color {
            get {
                return ((string)(this["PollOption1Color"]));
            }
            set {
                this["PollOption1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("219112147")]
        public string PollOption2Color {
            get {
                return ((string)(this["PollOption2Color"]));
            }
            set {
                this["PollOption2Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124252000")]
        public string PollOption3Color {
            get {
                return ((string)(this["PollOption3Color"]));
            }
            set {
                this["PollOption3Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255165000")]
        public string PollOption4Color {
            get {
                return ((string)(this["PollOption4Color"]));
            }
            set {
                this["PollOption4Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int _PollLeftMargin {
            get {
                return ((int)(this["_PollLeftMargin"]));
            }
            set {
                this["_PollLeftMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int _PollRightMargin {
            get {
                return ((int)(this["_PollRightMargin"]));
            }
            set {
                this["_PollRightMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int _PollTopMargin {
            get {
                return ((int)(this["_PollTopMargin"]));
            }
            set {
                this["_PollTopMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int _PollBottomMargin {
            get {
                return ((int)(this["_PollBottomMargin"]));
            }
            set {
                this["_PollBottomMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int _PollBarHeight {
            get {
                return ((int)(this["_PollBarHeight"]));
            }
            set {
                this["_PollBarHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int _PollBarWidth {
            get {
                return ((int)(this["_PollBarWidth"]));
            }
            set {
                this["_PollBarWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri")]
        public string _PollFontName {
            get {
                return ((string)(this["_PollFontName"]));
            }
            set {
                this["_PollFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public float _PollTitleSize {
            get {
                return ((float)(this["_PollTitleSize"]));
            }
            set {
                this["_PollTitleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255255255")]
        public string _PollTitleColor {
            get {
                return ((string)(this["_PollTitleColor"]));
            }
            set {
                this["_PollTitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float _PollCountSize {
            get {
                return ((float)(this["_PollCountSize"]));
            }
            set {
                this["_PollCountSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255255255")]
        public string _PollCountColor {
            get {
                return ((string)(this["_PollCountColor"]));
            }
            set {
                this["_PollCountColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public float _PollTotalSize {
            get {
                return ((float)(this["_PollTotalSize"]));
            }
            set {
                this["_PollTotalSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255255255")]
        public string _PollTotalColor {
            get {
                return ((string)(this["_PollTotalColor"]));
            }
            set {
                this["_PollTotalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int _PollTotalWidth {
            get {
                return ((int)(this["_PollTotalWidth"]));
            }
            set {
                this["_PollTotalWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int _PollBarSpacing {
            get {
                return ((int)(this["_PollBarSpacing"]));
            }
            set {
                this["_PollBarSpacing"] = value;
            }
        }
    }
}
